// Netlify Function: transparent proxy to an upstream NCM API deployment.
//
// Why this exists: the original api-enhanced codebase needs to refresh an
// anonymous_token + xeapi public key on every cold start, which is fragile
// on serverless (Netlify Functions have a 10s free-tier timeout and the
// upstream NCM register endpoint frequently rate-limits). Instead of
// running the full Express app here, this function forwards every request
// to a stable upstream deployment (e.g. a Vercel instance) that already
// handles token lifecycle, and just relays the response back.
//
// The proxy is method-agnostic (GET/POST/PUT/DELETE/OPTIONS), preserves
// query strings and request bodies, and forwards a minimal set of headers.
// Response headers from upstream (including Set-Cookie for login flows)
// are passed through unchanged.

const UPSTREAM = 'https://netease-cloud-music-api-mauve.vercel.app'

// Headers we forward to upstream. Host is dropped (would be the Netlify
// host, not the upstream's), and connection-level headers are hop-by-hop.
// Cookie is forwarded so logged-in flows (MUSIC_U) keep working.
const FORWARD_REQUEST_HEADERS = new Set([
  'accept',
  'accept-encoding',
  'accept-language',
  'content-type',
  'content-length',
  'user-agent',
  'cookie',
  'referer',
  'origin',
  'x-real-ip',
  'x-forwarded-for',
])

// Headers we relay back to the client. content-length is regenerated by
// Netlify, and connection-level headers are hop-by-hop. set-cookie is
// handled separately via multiValueHeaders.
const RELAY_RESPONSE_HEADERS = new Set([
  'content-type',
  'cache-control',
  'etag',
  'last-modified',
  'expires',
  'set-cookie',
  'access-control-allow-origin',
  'access-control-allow-methods',
  'access-control-allow-headers',
  'access-control-allow-credentials',
  'access-control-expose-headers',
  'access-control-max-age',
  'vary',
  'location',
])

// CORS headers we attach to every response so browser clients can call
// the proxy cross-origin. Upstream's own CORS headers (if any) are also
// relayed, but these defaults guarantee a permissive baseline.
const HANDLER_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
  'Access-Control-Allow-Headers':
    'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version, Cookie',
  'Access-Control-Allow-Credentials': 'true',
}

// Default UA when the client didn't send one. Some upstream NCM routes
// inspect User-Agent and reject empty/unknown values.
const DEFAULT_UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

exports.handler = async (event, context) => {
  // Handle CORS preflight without hitting upstream.
  if (event.httpMethod === 'OPTIONS') {
    return {
      statusCode: 204,
      headers: HANDLER_HEADERS,
      multiValueHeaders: {},
      body: '',
    }
  }

  // Build the upstream URL: original path + query string.
  // event.path is the URL-decoded path; event.queryStringParameters is
  // already an object. We re-encode to preserve special chars and
  // repeated keys (which Netlify collapses into multiValueQueryStringParameters).
  const path = event.path || '/'
  const upstreamUrl = new URL(path, UPSTREAM)
  const multiQuery = event.multiValueQueryStringParameters || {}
  const singleQuery = event.queryStringParameters || {}
  // Prefer multiValue (preserves repeated keys); fall back to single.
  const hasMulti = Object.keys(multiQuery).length > 0
  if (hasMulti) {
    Object.entries(multiQuery).forEach(([key, values]) => {
      values.forEach((v) => upstreamUrl.searchParams.append(key, v))
    })
  } else {
    Object.entries(singleQuery).forEach(([key, v]) => {
      upstreamUrl.searchParams.append(key, v)
    })
  }

  // Build forwarded headers.
  const inHeaders = event.headers || {}
  const upstreamHeaders = {}
  Object.entries(inHeaders).forEach(([name, value]) => {
    if (FORWARD_REQUEST_HEADERS.has(name.toLowerCase())) {
      upstreamHeaders[name] = value
    }
  })
  if (!upstreamHeaders['User-Agent'] && !upstreamHeaders['user-agent']) {
    upstreamHeaders['User-Agent'] = DEFAULT_UA
  }

  // Build request body. Netlify gives us event.body (string) and
  // event.isBase64Encoded. For binary uploads we need to decode back to
  // a Buffer; fetch accepts a string or Buffer/Uint8Array as body.
  let body
  if (event.body) {
    body = event.isBase64Encoded
      ? Buffer.from(event.body, 'base64')
      : event.body
  }

  let upstreamRes
  try {
    upstreamRes = await fetch(upstreamUrl, {
      method: event.httpMethod,
      headers: upstreamHeaders,
      body,
      redirect: 'manual',
    })
  } catch (err) {
    return {
      statusCode: 502,
      headers: { ...HANDLER_HEADERS, 'Content-Type': 'application/json' },
      multiValueHeaders: {},
      body: JSON.stringify({
        code: 502,
        msg:
          'upstream fetch failed: ' +
          (err && err.message ? err.message : String(err)),
      }),
    }
  }

  // Relay response headers. set-cookie goes into multiValueHeaders so all
  // cookies survive; everything else goes into headers (single value).
  const relayHeaders = { ...HANDLER_HEADERS }
  const relayMultiValueHeaders = {}
  upstreamRes.headers.forEach((value, name) => {
    const lower = name.toLowerCase()
    if (lower === 'set-cookie') {
      relayMultiValueHeaders['set-cookie'] =
        upstreamRes.headers.rawSetCookie || [value]
    } else if (RELAY_RESPONSE_HEADERS.has(lower)) {
      relayHeaders[name] = value
    }
  })

  // Read body as arraybuffer so we can handle both text and binary
  // (e.g. image/CAPTCHA responses) and base64-encode when needed.
  const buf = Buffer.from(await upstreamRes.arrayBuffer())
  const contentType = upstreamRes.headers.get('content-type') || ''
  const isText = /text|json|xml|javascript|utf-8/i.test(contentType)

  return {
    statusCode: upstreamRes.status,
    headers: relayHeaders,
    multiValueHeaders: relayMultiValueHeaders,
    body: isText ? buf.toString('utf-8') : buf.toString('base64'),
    isBase64Encoded: !isText,
  }
}
