// Netlify Edge Function: transparent proxy to an upstream NCM API deployment.
//
// Edge Functions run on Deno + Web standard APIs, deployed to Netlify's
// global edge network (close to users, low latency). Unlike serverless
// functions, they have no cold-start token-refresh problem because they
// don't run the NCM API locally — they just forward every request to a
// stable upstream deployment that already handles token lifecycle.
//
// The proxy is method-agnostic (GET/POST/PUT/DELETE/OPTIONS), preserves
// query strings and request bodies, and forwards a minimal set of
// headers. Response headers from upstream (including Set-Cookie for login
// flows) are passed through unchanged.

const UPSTREAM = 'https://netease-cloud-music-api-mauve.vercel.app'

// Headers we forward to upstream. Host is dropped (would be the Netlify
// host, not the upstream's), and connection-level headers are hop-by-hop.
// Cookie is forwarded so logged-in flows (MUSIC_U) keep working.
const FORWARD_REQUEST_HEADERS = new Set([
  'accept',
  'accept-encoding',
  'accept-language',
  'content-type',
  'content-length',
  'user-agent',
  'cookie',
  'referer',
  'origin',
  'x-real-ip',
  'x-forwarded-for',
])

// Headers we relay back to the client. content-length is regenerated by
// the edge runtime, and connection-level headers are hop-by-hop.
// set-cookie is handled specially below (relayed as an array).
const RELAY_RESPONSE_HEADERS = new Set([
  'content-type',
  'cache-control',
  'etag',
  'last-modified',
  'expires',
  'set-cookie',
  'access-control-allow-origin',
  'access-control-allow-credentials',
  'access-control-allow-methods',
  'access-control-allow-headers',
  'access-control-expose-headers',
  'access-control-max-age',
  'content-disposition',
  'content-language',
  'content-encoding',
  'vary',
  'date',
  'x-correlation-id',
])

// CORS headers attached to every response so browser apps can call this
// proxy directly. OPTIONS preflight is answered here without hitting
// upstream.
const CORS_HEADERS = {
  'access-control-allow-origin': '*',
  'access-control-allow-credentials': 'true',
  'access-control-allow-methods': 'GET, POST, PUT, DELETE, OPTIONS',
  'access-control-allow-headers':
    'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version, Cookie',
  'access-control-max-age': '86400',
}

const DEFAULT_UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

export default async (request, context) => {
  const method = request.method

  // Answer CORS preflight directly — no need to round-trip to upstream.
  if (method === 'OPTIONS') {
    return new Response(null, {
      status: 204,
      headers: CORS_HEADERS,
    })
  }

  // Reconstruct the upstream URL: original path + original query string.
  const url = new URL(request.url)
  const upstreamUrl = UPSTREAM + url.pathname + url.search

  // Build forwarded headers: start from CORS-safe defaults, then copy
  // whitelisted headers from the incoming request.
  const forwardHeaders = new Headers()
  forwardHeaders.set('user-agent', DEFAULT_UA)
  request.headers.forEach((value, name) => {
    if (FORWARD_REQUEST_HEADERS.has(name.toLowerCase())) {
      forwardHeaders.set(name, value)
    }
  })

  // Forward the request body as-is. For GET/HEAD there is no body; for
  // others, pass the stream through so large uploads don't get buffered.
  const init = {
    method,
    headers: forwardHeaders,
    redirect: 'manual',
  }
  if (method !== 'GET' && method !== 'HEAD') {
    init.body = request.body
    init.duplex = 'half'
  }

  let upstreamRes
  try {
    upstreamRes = await fetch(upstreamUrl, init)
  } catch (err) {
    return new Response(
      JSON.stringify({
        code: 502,
        msg:
          'upstream fetch failed: ' +
          (err && err.message ? err.message : String(err)),
      }),
      {
        status: 502,
        headers: { 'content-type': 'application/json', ...CORS_HEADERS },
      },
    )
  }

  // Relay response headers. set-cookie is special-cased because a response
  // may carry multiple Set-Cookie headers (login flows) and we must not
  // collapse them into one.
  const relayHeaders = new Headers(CORS_HEADERS)
  const setCookies = []
  upstreamRes.headers.forEach((value, name) => {
    const lower = name.toLowerCase()
    if (lower === 'set-cookie') {
      setCookies.push(value)
    } else if (RELAY_RESPONSE_HEADERS.has(lower)) {
      relayHeaders.set(name, value)
    }
  })

  // Build the response. Body is streamed straight from upstream — no
  // buffering, so binary responses (images, CAPTCHAs) and large JSON
  // both work without extra memory pressure.
  const response = new Response(upstreamRes.body, {
    status: upstreamRes.status,
    headers: relayHeaders,
  })
  // Apply multi Set-Cookie via headers.append (Response headers support
  // multiple values for the same name).
  for (const sc of setCookies) {
    response.headers.append('set-cookie', sc)
  }
  return response
}
